### ISSUE TITLE
Extensions for part 3

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/ggplot2-workshop-series#17]
- `patchwork`
- The brand new `marquee` package: https://www.tidyverse.org/blog/2024/05/marquee-0-1-0/ (lets you use markdown for axis labels and such, much overlap with `ggtext`)

**Comment by diazrenata** [comment]
* `gganimate` for animations? (we mentioned animation in the promo materials).
    * produce animated GIFS e.g. showing change over time
* `ggiraph` for interactivity?
    * hover effects
* `ggstatsplot` https://indrajeetpatil.github.io/ggstatsplot/articles/ggstatsplot.html
    * Pre-baked statistical analyses + results embedded in a ggplot
    * I have mixed feelings about this one - I guess I instinctively am cautious about a highly pre-baked solution as opposed to something more customizable.

**Comment by KristinaRiemer** [comment]
We did `gganimate` last year and were planning to do it again. There are some notes in the third session section of the [Hackmd](https://hackmd.io/fZJ5pD_9Q2eDd_tg8p3X0A).

**Comment by Aariq** [comment]
patchwork, gganimate, marquee (or ggtext) and ggiraph is probably plenty.

I can take patchwork (and marquee or ggtext), @KristinaRiemer can do gganimate again since she did that section last year IIRC, and maybe @diazrenata can take ggiraph (and marquee or ggtext)?

**Comment by Aariq** [comment]
We decided on extensions
